version: '3'
services:
  postgres:
    image: postgres:15.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
