version: '3'
services:
  postgres:
    image: postgres:15.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - backend
